export const templates = [
    {
      id: "landing-1",
      title: "现代企业登陆页",
      description: "适合初创企业和SaaS产品的现代、响应式登陆页模板",
      image: "/placeholder.svg?height=400&width=600",
      categories: ["登陆页面", "企业"],
      technologies: ["Next.js", "TypeScript", "Tailwind CSS", "shadcn/ui"],
      demoUrl: "#",
      githubUrl: "#",
    },
    {
      id: "ecommerce-1",
      title: "精品电子商务",
      description: "功能齐全的电子商务模板，带有产品展示、购物车和结账流程",
      image: "/placeholder.svg?height=400&width=600",
      categories: ["电子商务", "零售"],
      technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Stripe"],
      demoUrl: "#",
      githubUrl: "#",
    },
    {
      id: "blog-1",
      title: "内容创作者博客",
      description: "专为内容创作者设计的现代博客模板，支持MDX内容",
      image: "/placeholder.svg?height=400&width=600",
      categories: ["博客", "内容"],
      technologies: ["Next.js", "MDX", "Tailwind CSS", "Contentlayer"],
      demoUrl: "#",
      githubUrl: "#",
    },
    {
      id: "dashboard-1",
      title: "分析仪表盘",
      description: "带有图表、表格和数据可视化的管理仪表盘模板",
      image: "/placeholder.svg?height=400&width=600",
      categories: ["仪表盘", "管理"],
      technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Recharts"],
      demoUrl: "#",
      githubUrl: "#",
    },
    {
      id: "portfolio-1",
      title: "创意作品集",
      description: "展示您的项目和技能的现代作品集网站",
      image: "/placeholder.svg?height=400&width=600",
      categories: ["作品集", "个人"],
      technologies: ["Next.js", "Framer Motion", "Tailwind CSS"],
      demoUrl: "#",
      githubUrl: "#",
    },
    {
      id: "saas-1",
      title: "SaaS应用模板",
      description: "带有认证、定价页面和用户仪表盘的SaaS应用起始模板",
      image: "/placeholder.svg?height=400&width=600",
      categories: ["SaaS", "应用"],
      technologies: ["Next.js", "TypeScript", "Tailwind CSS", "NextAuth.js"],
      demoUrl: "#",
      githubUrl: "#",
    },
    {
      id: "landing-2",
      title: "产品登陆页",
      description: "专为产品展示设计的高转化率登陆页模板",
      image: "/placeholder.svg?height=400&width=600",
      categories: ["登陆页面", "产品"],
      technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
      demoUrl: "#",
      githubUrl: "#",
    },
    {
      id: "dashboard-2",
      title: "管理控制台",
      description: "完整的管理控制台模板，带有用户管理和设置页面",
      image: "/placeholder.svg?height=400&width=600",
      categories: ["仪表盘", "管理"],
      technologies: ["Next.js", "TypeScript", "Tailwind CSS", "shadcn/ui"],
      demoUrl: "#",
      githubUrl: "#",
    },
    {
      id: "blog-2",
      title: "杂志风格博客",
      description: "杂志风格的博客模板，适合新闻和媒体网站",
      image: "/placeholder.svg?height=400&width=600",
      categories: ["博客", "媒体"],
      technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Sanity.io"],
      demoUrl: "#",
      githubUrl: "#",
    },
  ]
  